# Generated by Django 4.2.1 on 2023-05-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(default=1, max_length=18),
            preserve_default=False,
        ),
    ]
