# Generated by Django 4.2.1 on 2023-05-22 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_cliente_documento_alter_cliente_contato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aparelho', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=20)),
                ('serial', models.CharField(max_length=20)),
                ('observacao', models.TextField()),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contatos.cliente')),
            ],
        ),
    ]
